version: "3.8"

services:
  web:
    image: vigneshshettyin/rss-buddy:latest
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      default:

networks:
  default:
    external: true
