
services:
  web:
    image: vigneshshettyin/rss-buddy:latest
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      nginx-proxy-manager_default:
        ipv4_address: 172.18.0.3

networks:
  nginx-proxy-manager_default:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
