version: "3.8"

services:
  web:
    image: vigneshshettyin/rss-buddy:latest
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      app-network:
        ipv4_address: 172.30.0.10

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
